/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "rocksdb_constants.h"

namespace dsn { namespace apps {

const rocksdbConstants g_rocksdb_constants;

rocksdbConstants::rocksdbConstants() {
}

}} // namespace

