/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef rocksdb_CONSTANTS_H
#define rocksdb_CONSTANTS_H

#include "rocksdb_types.h"

namespace dsn { namespace apps {

class rocksdbConstants {
 public:
  rocksdbConstants();

};

extern const rocksdbConstants g_rocksdb_constants;

}} // namespace

#endif
