/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "rrdb_constants.h"

namespace dsn { namespace apps {

const rrdbConstants g_rrdb_constants;

rrdbConstants::rrdbConstants() {
}

}} // namespace

