/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef rrdb_TYPES_H
#define rrdb_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace dsn { namespace apps {

class put_req;

class put_resp;

class get_req;

class get_resp;

typedef struct _put_req__isset {
  _put_req__isset() : key(false), value(false) {}
  bool key :1;
  bool value :1;
} _put_req__isset;

class put_req {
 public:

  put_req(const put_req&);
  put_req& operator=(const put_req&);
  put_req() : key(), value() {
  }

  virtual ~put_req() throw();
  std::string key;
  std::string value;

  _put_req__isset __isset;

  void __set_key(const std::string& val);

  void __set_value(const std::string& val);

  bool operator == (const put_req & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const put_req &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const put_req & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(put_req &a, put_req &b);

inline std::ostream& operator<<(std::ostream& out, const put_req& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _put_resp__isset {
  _put_resp__isset() : err(false) {}
  bool err :1;
} _put_resp__isset;

class put_resp {
 public:

  put_resp(const put_resp&);
  put_resp& operator=(const put_resp&);
  put_resp() : err(0) {
  }

  virtual ~put_resp() throw();
  int32_t err;

  _put_resp__isset __isset;

  void __set_err(const int32_t val);

  bool operator == (const put_resp & rhs) const
  {
    if (!(err == rhs.err))
      return false;
    return true;
  }
  bool operator != (const put_resp &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const put_resp & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(put_resp &a, put_resp &b);

inline std::ostream& operator<<(std::ostream& out, const put_resp& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _get_req__isset {
  _get_req__isset() : key(false) {}
  bool key :1;
} _get_req__isset;

class get_req {
 public:

  get_req(const get_req&);
  get_req& operator=(const get_req&);
  get_req() : key() {
  }

  virtual ~get_req() throw();
  std::string key;

  _get_req__isset __isset;

  void __set_key(const std::string& val);

  bool operator == (const get_req & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const get_req &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const get_req & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(get_req &a, get_req &b);

inline std::ostream& operator<<(std::ostream& out, const get_req& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _get_resp__isset {
  _get_resp__isset() : err(false), value(false) {}
  bool err :1;
  bool value :1;
} _get_resp__isset;

class get_resp {
 public:

  get_resp(const get_resp&);
  get_resp& operator=(const get_resp&);
  get_resp() : err(0), value() {
  }

  virtual ~get_resp() throw();
  int32_t err;
  std::string value;

  _get_resp__isset __isset;

  void __set_err(const int32_t val);

  void __set_value(const std::string& val);

  bool operator == (const get_resp & rhs) const
  {
    if (!(err == rhs.err))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const get_resp &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const get_resp & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(get_resp &a, get_resp &b);

inline std::ostream& operator<<(std::ostream& out, const get_resp& obj)
{
  obj.printTo(out);
  return out;
}

}} // namespace

#endif
