/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef rrdb_CONSTANTS_H
#define rrdb_CONSTANTS_H

#include "rrdb_types.h"

namespace dsn { namespace apps {

class rrdbConstants {
 public:
  rrdbConstants();

};

extern const rrdbConstants g_rrdb_constants;

}} // namespace

#endif
